import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";
import Banner from "@/components/Banner";
import { Footer } from "@/components/footer";


export const metadata: Metadata = {
  title: "Blog Ghost",
  description: "Generated by Samuel Lajara",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
