import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "IA Lusery",
  description: "Generated by Samuel Lajara & Sebas Arriaza",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="max-w-7xl mx-auto">{children}</body>
    </html>
  );
}
