import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Blog Ghost",
  description: "Generated by Samuel Lajara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="max-w-7xl mx-auto">
        {children}
      </body>
    </html>
  );
}
