/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DtFvEeyA9Vo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Syne } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function LandingPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-background px-4">
      <div className="mx-auto flex max-w-2xl flex-col items-center justify-between gap-16 text-center sm:gap-8">
        <h1 className="font-mono bg-gradient-to-r from-primary to-slate-400 bg-clip-text text-6xl font-extrabold text-transparent">
          LuseryLabs
        </h1>
        <p className="text-2xl text-muted-foreground">
          Explore the latest insights and trends in artificial intelligence at LuseryLabs.
        </p>
        <Link
          href="/ai"
          className="inline-flex items-center justify-center rounded-md bg-slate-300 px-5 py-3 text-lg font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2"
          prefetch={false}
        >
          Enter
        </Link>
      </div>
    </main>
  )
}
